### ISSUE TITLE
куки селениума

### ISSUE THREAD

**Issue by slehernaf** [pythontoday/selenium_python#2]
Доброго времени суток, я у меня возникли проблемы с авторизацией через куки.
Пробовал сначала авторизовываться в https://vk.com, и авторизация даже проходила, но после нее, буквально через пол секунды выдавало ошибку "ERR_TOO_MANY_REDIRECTS", удаление и перезапись кук файла, а так же очистка браузера от всех куков не помогла.
![ ](https://github.com/slehernaf/pip/blob/main/FgqrYgybbOs.jpg?raw=true)
Потом попробовал авторизоваться на другом сайте по такому же методу, и тут уже авторизация по кукам вообще не проходила, хотя вроде бы весь код простой и в нем сложно было ошибиться(первичную авторизацию провожу вручную):
```
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time
import pickle

options = webdriver.ChromeOptions()

options.add_argument("user-agent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0")
driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),
                          options=options
                          )
try:
    url = "https://gamebomb.ru/gbusers/login"
    # driver.get(url)
    # time.sleep(25)
    # pickle.dump(driver.get_cookies(), open(f"cookie", "wb"))

    driver.get(url)
    time.sleep(5)

    for cookie in pickle.load(open(f"cookies", "rb")):
        driver.add_cookie(cookie)

    time.sleep(5)
    driver.refresh()
    time.sleep(15)

except Exception as ex:
    print(ex)
finally:
    driver.close()
    driver.quit()
``` 

Попробовал тоже самое на виртуальной машине через firefox, через ВК проходит аутентификация и примерно через секунду, выходит из аккаунта.

**Comment by Staks-sor** [comment]
Защита может на самих платформах стоит. Пробовал кроме этих где по проще?

**Comment by slehernaf** [comment]
> 

Да, в принципе на тех что-проще все работает, посмотрел еще в интернете и на каком-то форуме от 16 года была информация, что из-за перехода вк на новый дизайн, он выдает пару похожих куков с разным сроком жизни, и браузер берет те что живут дольше, подумал что возможно и сейчас примерно такой же прикол вернулся.
P.S. впринципе все решилось при добавлении двух аргументов:
`options.add_argument(r'user-data-dir=C:\Users\User sName\AppData\Local\Google\Chrome\User Data')`
`options.add_argument('--profile-directory=Profile 1')`
Но это не помогает при заходе в режиме `headless = True`, что печально, и сейчас думаю можно ли это как-то исправить...

**Comment by slehernaf** [comment]
> Защита может на самих платформах стоит. Пробовал кроме этих где по проще?

> 

Да, в принципе на тех что-проще все работает, посмотрел еще в интернете и на каком-то форуме от 16 года была информация, что из-за перехода вк на новый дизайн, он выдает пару похожих куков с разным сроком жизни, и браузер берет те что живут дольше, подумал что возможно и сейчас примерно такой же прикол вернулся.
P.S. впринципе все решилось при добавлении двух аргументов:
`options.add_argument(r'user-data-dir=C:\Users\User sName\AppData\Local\Google\Chrome\User Data')`
`options.add_argument('--profile-directory=Profile 1')`
Но это не помогает при заходе в режиме `headless = True`, что печально, и сейчас думаю можно ли это как-то исправить...

**Comment by Staks-sor** [comment]
сам не пытался так как это было не нужно, что если попробовать не через куки а через ключ заходить? Или принципиально через куки надо?

**Comment by slehernaf** [comment]
> сам не пытался так как это было не нужно, что если попробовать не через куки а через ключ заходить? Или принципиально через куки надо?

Что подразумевается под использованием ключа?

**Comment by slehernaf** [comment]
Мискликнул и случайно закрыл...

**Comment by slehernaf** [comment]
Мискликнул и случайно закрыл...

**Comment by Staks-sor** [comment]
Ты же можешь по айпи связываться через аутз, домой приду смогу подробней написать, ну это работает только для тех к кому есть доступ что бы получить этот аутз

**Comment by Staks-sor** [comment]
Способ №1 (Для получения токена ВОРКЕРА)

    1) Подставляем свой логин и пароль в ссылку: [https://oauth.vk.com/token?grant_type=password&client_id=6146827&client_secret=qVxWRF1CwHERuIrKBnqe&username=логин&password=пароль&v=5.131&2fa_supported=1](https://oauth.vk.com/token?grant_type=password&client_id=6146827&client_secret=qVxWRF1CwHERuIrKBnqe&username=%D0%BB%D0%BE%D0%B3%D0%B8%D0%BD&password=%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8C&v=5.131&2fa_supported=1) 

2) Получаете ответ в виде:  {"access_token":"24c74df422dee18f4cea28626ba2465a9359b2662f20d10161daa3f853ca6075eb6fd0333e8xxxxxxx","expires_in":0,"user_id":1}

вот вчера забыл написать, через этот токен вполне можно отлично взаимодействовать с вк

**Comment by slehernaf** [comment]
> Способ №1 (Для получения токена ВОРКЕРА)
> 
> ```
> 1) Подставляем свой логин и пароль в ссылку: [https://oauth.vk.com/token?grant_type=password&client_id=6146827&client_secret=qVxWRF1CwHERuIrKBnqe&username=логин&password=пароль&v=5.131&2fa_supported=1](https://oauth.vk.com/token?grant_type=password&client_id=6146827&client_secret=qVxWRF1CwHERuIrKBnqe&username=%D0%BB%D0%BE%D0%B3%D0%B8%D0%BD&password=%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D1%8C&v=5.131&2fa_supported=1) 
> ```
> 
> 2. Получаете ответ в виде:  {"access_token":"24c74df422dee18f4cea28626ba2465a9359b2662f20d10161daa3f853ca6075eb6fd0333e8xxxxxxx","expires_in":0,"user_id":1}
> 
> вот вчера забыл написать, через этот токен вполне можно отлично взаимодействовать с вк

Ясно, спасибо
